package de.gruenderelf.engine

import kotlin.math.abs
import kotlin.math.roundToInt

fun Player.personalityType(season:Int):PersonalityType{
 val age=season-birthYear
 return when{
  hidden.pressure>=78&&hidden.consistency>=72->PersonalityType.BIG_GAME
  hidden.professionalism>=78&&hidden.loyalty>=65->PersonalityType.PROFESSIONAL
  hidden.pressure<=36&&hidden.ambition>=55->PersonalityType.CHOKER
  ca>=72&&hidden.professionalism<=38->PersonalityType.LAZY_STAR
  age<=21&&hidden.ambition>=72&&hidden.consistency<=58->PersonalityType.WILD_YOUNGSTER
  hidden.pressure>=68&&hidden.professionalism>=65&&age>=27->PersonalityType.LEADER
  else->PersonalityType.BALANCED
 }
}

fun Player.effectiveRole():PlayerRole = if(role!=PlayerRole.AUTO)role else when(position){
 Position.TW->PlayerRole.BUILD_UP_KEEPER
 Position.IV->if(attributes.passing+attributes.vision>=attributes.tackling+attributes.strength)PlayerRole.BALL_PLAYING_CB else PlayerRole.STOPPER
 Position.LV,Position.RV->if(attributes.pace+attributes.stamina>=attributes.tackling+attributes.strength)PlayerRole.OVERLAPPING_FULLBACK else PlayerRole.INVERTED_FULLBACK
 Position.DM->if(attributes.passing+attributes.vision>=attributes.tackling+attributes.strength)PlayerRole.DEEP_PLAYMAKER else PlayerRole.ANCHOR
 Position.ZM->PlayerRole.BOX_TO_BOX
 Position.OM->PlayerRole.PLAYMAKER
 Position.LA,Position.RA->if(attributes.finishing>=attributes.passing)PlayerRole.INSIDE_FORWARD else PlayerRole.WINGER
 Position.ST->when{attributes.strength+attributes.heading>attributes.pace+attributes.technique+8->PlayerRole.TARGET_FORWARD;attributes.stamina+hidden.professionalism>135->PlayerRole.PRESSING_FORWARD;else->PlayerRole.POACHER}
}

object ClubSystems {
 fun clamp(c:Club){with(c.dynamics){chemistry=chemistry.coerceIn(0,100);tacticalUnderstanding=tacticalUnderstanding.coerceIn(0,100);pressingCoordination=pressingCoordination.coerceIn(0,100);mentalHardness=mentalHardness.coerceIn(0,100);leadership=leadership.coerceIn(0,100);hierarchyStability=hierarchyStability.coerceIn(0,100);languageCohesion=languageCohesion.coerceIn(0,100);fatigueLoad=fatigueLoad.coerceIn(0,100);opponentPrep=opponentPrep.coerceIn(0,100);staffQuality=staffQuality.coerceIn(10,100);patterns.keys.toList().forEach{patterns[it]=(patterns[it]?:0).coerceIn(0,100)}}}
 fun relationKey(a:Int,b:Int)=if(a<b)"$a:$b" else "$b:$a"
 fun clubRelation(w:World,a:Int,b:Int)=w.clubRelations[relationKey(a,b)]?:50
 fun changeClubRelation(w:World,a:Int,b:Int,delta:Int){val k=relationKey(a,b);w.clubRelations[k]=((w.clubRelations[k]?:50)+delta).coerceIn(0,100)}
}

object YouthEngine {
 fun readiness(w:World,p:Player):Int{
  val c=w.clubs[p.clubId]?:return 0;val y=p.youthProfile;val age=w.calendar.season-p.birthYear
  val roleFit=if(y.roleSpark==PlayerRole.AUTO||y.roleSpark==p.effectiveRole())10 else 0
  val physical=((p.attributes.strength+p.attributes.stamina+p.attributes.pace)/3.0).roundToInt()
  val mental=(p.hidden.professionalism+p.hidden.pressure+y.maturity)/3
  val level=(p.ca*42+physical*18+mental*22+y.confidence*8+c.dynamics.tacticalUnderstanding*10)/100
  val ageGate=when{age<=15->-16;age==16->-8;age>=19->5;else->0}
  return (level+roleFit+ageGate-y.schoolStress/8-y.injuryGrowthRisk/10).coerceIn(0,100)
 }
 fun riskLabel(w:World,p:Player):String{val y=p.youthProfile;val ready=readiness(w,p);return when{y.growthSpurtWeeks>0->"Wachstumsschub: Belastung begrenzen";y.schoolStress>=70->"Schulstress hoch";y.adviserPressure>=75->"Berater drängt auf nächsten Schritt";ready<45->"Profifußball wäre aktuell Überforderung";ready<65->"Dosierte Profi-Minuten sinnvoll";else->"Bereit für echte Kaderchancen"}}
 fun configureClub(c:Club){
  if(c.academy.identity==AcademyIdentity.BALANCED)c.academy.identity=when(c.youthPhilosophy){"Leistungsförderung"->AcademyIdentity.POSSESSION;"Breitensport"->AcademyIdentity.ATHLETIC;else->when(c.playPhilosophy){"Direkt nach vorn"->AcademyIdentity.ATHLETIC;"Ballbesitz"->AcademyIdentity.POSSESSION;else->AcademyIdentity.STREET}}
  c.academy.scouting=maxOf(c.academy.scouting,(c.stadium.youth*.75).roundToInt());c.academy.u19Quality=maxOf(c.academy.u19Quality,(c.stadium.youth*.70).roundToInt());c.academy.u23Quality=maxOf(c.academy.u23Quality,(c.stadium.training*.55).roundToInt());c.dynamics.staffQuality=maxOf(c.dynamics.staffQuality,((c.stadium.training+c.stadium.youth+c.stadium.medicine)/3.0).roundToInt())
 }
 fun seedProfile(w:World,c:Club,p:Player,rng:SeededRandom){configureClub(c);val golden=c.academy.goldenGeneration;val identity=c.academy.identity
  p.youthProfile=YouthProfile(learning=(45+c.academy.scouting/4+rng.int(0,30)+(if(golden)6 else 0)).coerceAtMost(99),maturity=rng.int(35,72),path=when(rng.int(0,99)){in 0..16->DevelopmentPath.EARLY;in 17..32->DevelopmentPath.LATE;in 33..38->DevelopmentPath.PLATEAU;else->DevelopmentPath.NORMAL},familySupport=rng.int(35,90),adviserPressure=rng.int(15,72),schoolStress=rng.int(10,58),injuryGrowthRisk=rng.int(10,45),roleSpark=when(identity){AcademyIdentity.POSSESSION->rng.pick(listOf(PlayerRole.PLAYMAKER,PlayerRole.DEEP_PLAYMAKER,PlayerRole.BALL_PLAYING_CB));AcademyIdentity.ATHLETIC->rng.pick(listOf(PlayerRole.PRESSING_FORWARD,PlayerRole.OVERLAPPING_FULLBACK,PlayerRole.BOX_TO_BOX));AcademyIdentity.STREET->rng.pick(listOf(PlayerRole.INSIDE_FORWARD,PlayerRole.PLAYMAKER,PlayerRole.POACHER));AcademyIdentity.DEFENSIVE->rng.pick(listOf(PlayerRole.STOPPER,PlayerRole.ANCHOR,PlayerRole.INVERTED_FULLBACK));AcademyIdentity.PRESSING->rng.pick(listOf(PlayerRole.PRESSING_FORWARD,PlayerRole.BOX_TO_BOX,PlayerRole.OVERLAPPING_FULLBACK));else->PlayerRole.AUTO},homegrownYears=1)
 }
 fun weekly(w:World,rng:SeededRandom){
  for(c in w.clubs.values){configureClub(c);for(p in w.squad(c.id).filter{it.youth || w.calendar.season-it.birthYear<=21}){val y=p.youthProfile;val age=w.calendar.season-p.birthYear
    val minutesDelta=(p.stats.minutes-y.lastTrackedMinutes).coerceAtLeast(0);y.lastTrackedMinutes=p.stats.minutes
    if(y.growthSpurtWeeks>0)y.growthSpurtWeeks-- else if(age in 15..18&&rng.chance(.018)){y.growthSpurtWeeks=rng.int(2,5);y.injuryGrowthRisk=(y.injuryGrowthRisk+18).coerceAtMost(100)}
    val target=when{age<=16->0;age==17->25;age==18->45;else->65}
    val overload=(minutesDelta-target).coerceAtLeast(0);val under=(target/2-minutesDelta).coerceAtLeast(0)
    if(overload>0){y.confidence=(y.confidence+2).coerceAtMost(100);p.fitness=(p.fitness-overload*.05).coerceAtLeast(20.0);y.injuryGrowthRisk=(y.injuryGrowthRisk+overload/6).coerceAtMost(100)}
    if(under>0&&age>=18)y.confidence=(y.confidence-1).coerceAtLeast(10)
    if(y.mentorId==0)y.mentorId=w.squad(c.id).filter{!it.youth&&w.calendar.season-it.birthYear>=25}.maxByOrNull{it.hidden.professionalism+it.hidden.pressure+it.hidden.consistency}?.id?:0
    val mentor=w.players[y.mentorId];if(mentor?.clubId==c.id&&mentor.hidden.professionalism>=65){y.maturity=(y.maturity+1).coerceAtMost(100);p.hidden.professionalism=(p.hidden.professionalism+1).coerceAtMost(100)}
    if(y.seniorTraining){y.maturity=(y.maturity+1).coerceAtMost(100);p.sharpness=(p.sharpness+2).coerceAtMost(100);if(c.dynamics.fatigueLoad>70)p.fitness=(p.fitness-1.5).coerceAtLeast(20.0)}
    val spark=if(y.roleSpark==p.effectiveRole())1.28 else 1.0;val path=when(y.path){DevelopmentPath.EARLY->if(age<=19)1.25 else .75;DevelopmentPath.LATE->if(age>=19)1.30 else .72;DevelopmentPath.PLATEAU->.42;DevelopmentPath.BREAKTHROUGH->1.55;DevelopmentPath.CRASH->.25;else->1.0};val ecosystem=if(age<=18)c.academy.u19Quality else c.academy.u23Quality
    p.trainingProgress+=.014*(.55+y.learning/100.0)*(1+c.stadium.youth/140.0+ecosystem/240.0)*spark*path
    if(p.trainingProgress>=1.0){p.trainingProgress-=1.0;p.attributes.improve(rng.pick(Focus.entries),p.hidden.potential)}
    if(y.adviserPressure>82&&readiness(w,p)>68&&rng.chance(.04)){p.wantsMove=true;p.morale=(p.morale-4).coerceAtLeast(5)}
    if(y.schoolStress>75)p.sharpness=(p.sharpness-2).coerceAtLeast(0);if(y.familySupport<35&&p.hidden.professionalism<45&&rng.chance(.025)){p.morale=(p.morale-5).coerceAtLeast(5);y.confidence=(y.confidence-4).coerceAtLeast(5);y.schoolStress=(y.schoolStress+4).coerceAtMost(100)}
    y.homegrownYears=(y.homegrownYears+if(w.calendar.absoluteWeek%40==0)1 else 0).coerceAtMost(20)
   }}
 }
 fun newSeason(w:World,rng:SeededRandom){for(c in w.clubs.values){configureClub(c);val cycle=(c.academy.generationCycle+rng.int(-18,18)+(c.academy.scouting-50)/6).coerceIn(0,100);c.academy.generationCycle=cycle;c.academy.goldenGeneration=cycle>=78;if(c.academy.goldenGeneration)c.academy.droughtYears=0 else c.academy.droughtYears++}}
}

object TrainingSystems {
 private fun aiPlan(c:Club):TrainingPlan{val tactical=if(c.tactics.pressing>=4)UnitType.TACTICS else UnitType.POSITIONAL;val technical=if(c.tactics.buildUp in listOf(BuildUp.SHORT,BuildUp.TIKI_TAKA))UnitType.TECHNIQUE else UnitType.DUELS;return TrainingPlan(mutableListOf(UnitType.RECOVERY,tactical,UnitType.VIDEO,technical,UnitType.FITNESS,UnitType.SET_PIECES,UnitType.OFF),intensity=if(c.dynamics.fatigueLoad>65)2 else 3)}
 fun planFor(w:World,c:Club)=if(c.id==w.user.clubId){if(w.assistantCoach.autoSeniorTraining)AssistantCoachSystem.prepareUserPlan(w) else w.training}else aiPlan(c)
 fun effectiveDays(w:World,c:Club,plan:TrainingPlan):List<Int>{val cap=if(!w.privateTopClubMode&&c.tier>=7)3 else 7;return plan.days.indices.filter{plan.days[it] !in listOf(UnitType.OFF,UnitType.RECOVERY)}.take(cap)}
 fun applyAll(w:World)=w.random{rng->
  for(c in w.clubs.values){AssistantCoachSystem.prepareYouth(w,c);val plan=planFor(w,c);val effective=effectiveDays(w,c,plan);val sessions=effective.map{plan.days[it]};val report=TrainingReport(w.calendar.absoluteWeek,effectiveDays=effective);val intensity=plan.intensity.coerceIn(1,5);val staff=(.55+c.dynamics.staffQuality/100.0*.45)
   val load=(sessions.sumOf{maxOf(0,it.load)}*intensity/3.0).roundToInt();c.dynamics.fatigueLoad=(c.dynamics.fatigueLoad+load-sessions.count{it==UnitType.RECOVERY}*5-plan.days.count{it==UnitType.OFF}*4).coerceIn(0,100)
   fun add(v:Int,delta:Double)=(v+delta*staff).roundToInt().coerceIn(0,100)
   // Amateur clubs still have a cap for physically demanding training days. Low-load classroom/team units
   // (video, bonding, mental work, set pieces) must nevertheless create the tactical effect the manager selected.
   val videoUnits=plan.days.count{it==UnitType.VIDEO};val bondingUnits=plan.days.count{it==UnitType.TEAM_BONDING};val mentalUnits=plan.days.count{it==UnitType.MENTAL};val setPieceUnits=plan.days.count{it==UnitType.SET_PIECES}
   val tactics=sessions.count{it in listOf(UnitType.TACTICS,UnitType.POSITIONAL,UnitType.GAME)}+videoUnits;val press=sessions.count{it in listOf(UnitType.TACTICS,UnitType.DUELS,UnitType.GAME)};val mental=sessions.count{it==UnitType.GAME}+mentalUnits+bondingUnits
   val next=w.fixtures.filter{!it.played&&(it.homeId==c.id||it.awayId==c.id)}.minByOrNull{it.matchday};val secretBoost=if(plan.secretSession&&next!=null&&(w.isDerby(next.homeId,next.awayId)||CompetitionEngine.isDecisiveKnockoutFixture(w,next)))4.0 else 0.0
   c.dynamics.tacticalUnderstanding=add(c.dynamics.tacticalUnderstanding,tactics*1.5+secretBoost*.35);c.dynamics.pressingCoordination=add(c.dynamics.pressingCoordination,press*1.25);c.dynamics.mentalHardness=add(c.dynamics.mentalHardness,mentalUnits*2.2+secretBoost*.25);c.dynamics.chemistry=add(c.dynamics.chemistry,mental*1.8-(if(intensity>=5)2.5 else 0.0));c.dynamics.leadership=add(c.dynamics.leadership,mentalUnits*1.2);c.dynamics.hierarchyStability=add(c.dynamics.hierarchyStability,bondingUnits*2.0-(if(intensity>=5)1.0 else 0.0));c.dynamics.opponentPrep=add(c.dynamics.opponentPrep,(if(plan.opponentPrep)(videoUnits+sessions.count{it==UnitType.TACTICS})*3.0 else -2.0)+secretBoost);if(secretBoost>0)c.dynamics.fatigueLoad=(c.dynamics.fatigueLoad+3).coerceAtMost(100)
   val patterns=c.dynamics.patterns;fun pat(k:String,d:Double){patterns[k]=add(patterns[k]?:25,d)};pat("AUFBAU",sessions.count{it==UnitType.POSITIONAL||it==UnitType.TECHNIQUE}*2.0);pat("PRESSINGFALLE",sessions.count{it==UnitType.TACTICS||it==UnitType.DUELS}*1.8);pat("HALBRAUM",sessions.count{it==UnitType.POSITIONAL}*2.2);pat("FLUEGEL",sessions.count{it==UnitType.TACTICS||it==UnitType.TECHNIQUE}*1.1);pat("DIAGONALE",sessions.count{it==UnitType.TECHNIQUE||it==UnitType.VIDEO}*1.3);pat("RESTVERTEIDIGUNG",sessions.count{it==UnitType.TACTICS||it==UnitType.POSITIONAL}*1.8);pat("STANDARDS",setPieceUnits*3.2)
   val majority=w.squad(c.id).groupingBy{it.nationality}.eachCount().maxByOrNull{it.value}?.key;val languageBonus=w.squad(c.id).count{it.nationality==majority};c.dynamics.languageCohesion=add(c.dynamics.languageCohesion,(languageBonus-w.squad(c.id).size/2)*.08+sessions.count{it==UnitType.TEAM_BONDING}*.8)
   for(p in w.squad(c.id).filter{!it.retired&&(!it.youth||it.youthProfile.seniorTraining||w.intensiveTraining.any{pr->pr.playerId==it.id})}){if(p.injuryWeeks>0)continue;val blocked=p.unavailableReason in listOf(UnavailableReason.WORK,UnavailableReason.HOLIDAY,UnavailableReason.RESERVE);val recovery=plan.days.count{it==UnitType.RECOVERY}*3.0+plan.days.count{it==UnitType.OFF}*1.3;p.fitness=(p.fitness-(if(blocked)0.0 else load*.36)+recovery).coerceIn(5.0,100.0);if(blocked)continue;p.sharpness=(p.sharpness+sessions.size*2-intensity/2).coerceIn(0,100)
    val foci=sessions.mapNotNull{when(it){UnitType.TECHNIQUE,UnitType.POSITIONAL->Focus.TECHNIQUE;UnitType.TACTICS,UnitType.VIDEO,UnitType.GAME,UnitType.MENTAL,UnitType.TEAM_BONDING->Focus.VISION;UnitType.FITNESS->Focus.PACE;UnitType.DUELS->Focus.TACKLING;UnitType.FINISHING,UnitType.SET_PIECES->Focus.FINISHING;UnitType.GOALKEEPING->if(p.position==Position.TW)Focus.KEEPING else null;else->null}}+(if(c.id==w.user.clubId)plan.extra.filter{it.playerId==p.id}.map{it.focus}else emptyList())
    val age=w.calendar.season-p.birthYear;val ageEffect=when{age<23->1.2;age>33->.25;else->.7};p.trainingProgress+=foci.size*.026*(1+c.stadium.training*.009+c.stadium.gym*.004)*(.5+p.hidden.professionalism*.01)*ageEffect*staff
    if(p.trainingProgress>=1&&foci.isNotEmpty()){p.trainingProgress-=1;val focus=rng.pick(foci);if(p.attributes.improve(focus,p.hidden.potential)&&c.id==w.user.clubId)report.gains.add("${p.name}: ${focus.label} +1")}
    IntensiveTrainingSystem.applyWeek(w,c,p,report,rng)
    val risk=sessions.count{it==UnitType.FITNESS||it==UnitType.DUELS||it==UnitType.GAME}*.0045*intensity/3.0*(1+p.hidden.injuryProneness*.01)*(1-c.stadium.medicine*.006)*(if(p.fitness<50)2.0 else 1.0)*(if(p.youthProfile.growthSpurtWeeks>0)1.6 else 1.0)
    if(rng.chance(risk)){p.injuryWeeks=rng.int(1,3)+1;p.injury="Trainingszerrung";if(c.id==w.user.clubId)report.injuries.add("${p.name}: ${p.injuryWeeks-1} Wochen")}
   }
   ClubSystems.clamp(c);if(c.id==w.user.clubId){if(setPieceUnits>0)report.effects.add("Standards-Automatisierung ${c.dynamics.patterns["STANDARDS"]?:30}/100");report.averageFitness=w.squad().map{it.fitness}.average().roundToInt();report.effects.add("Chemie ${c.dynamics.chemistry}/100 · Taktik ${c.dynamics.tacticalUnderstanding}/100 · Pressing ${c.dynamics.pressingCoordination}/100");report.effects.add("Belastung ${c.dynamics.fatigueLoad}/100 · Gegnervorbereitung ${c.dynamics.opponentPrep}/100");w.training.lastReport=report}
  };YouthEngine.weekly(w,rng);YouthCompetitionSystem.weekly(w,rng);ScoutingTransferSystem.weekly(w,rng);OutboundTransferSystem.weekly(w,rng);TransferEngine.aiMarket(w,rng)
 }
}

private fun Player.targetYouthSquadApply(target:YouthSquad?){if(target!=null){youth=true;youthSquad=target}else youth=false}

object TransferEngine {
 fun marketValue(w:World,p:Player):Long{val age=w.calendar.season-p.birthYear;val ageFactor=when{age<=20->1.45;age<=24->1.25;age<=29->1.0;age<=32->.78;else->.45};val base=p.ca*p.ca*850L;val potential=1.0+(p.hidden.potential-p.ca).coerceAtLeast(0)/90.0;return (base*ageFactor*potential).toLong().coerceAtLeast(500L)}
 private fun roleScore(role:SquadRole)=when(role){SquadRole.STAR->95;SquadRole.STARTER->82;SquadRole.ROTATION->65;SquadRole.PROSPECT->58;SquadRole.BACKUP->42}
 fun askingPrice(w:World,seller:Club?,p:Player,type:DealType):Long{if(seller==null)return 0;val value=marketValue(w,p);val importance=if(p.id in seller.tactics.xi)1.35 else if(p.id in seller.tactics.bench)1.10 else .92;val financial=if(seller.budget<0).78 else if(seller.budget<value/3).92 else 1.05;val homegrown=if(p.homegrownClubId==seller.id)1.12 else 1.0;val willingness=if(p.wantsMove).78 else 1.0;val natural=when(type){DealType.LOAN,DealType.LOAN_OPTION->(value*.06*importance).toLong();else->(value*importance*financial*homegrown*willingness).toLong()};return if(type in listOf(DealType.BUY,DealType.SWAP)&&p.releaseClause>0)minOf(natural,p.releaseClause) else natural}
 fun createOffer(w:World,buyerClubId:Int,playerId:Int,type:DealType=DealType.BUY,role:SquadRole=SquadRole.ROTATION):TransferOffer{val p=w.players.getValue(playerId);require(!p.retired&&p.clubId!=buyerClubId);val buyer=w.clubs.getValue(buyerClubId);val ownerId=if(p.loanParentClubId!=0)p.loanParentClubId else p.clubId;val seller=w.clubs[ownerId];val ask=askingPrice(w,seller,p,type);val wage=maxOf(5,(p.wage*1.18).roundToInt(),(marketValue(w,p)/42000L).toInt());val swap=if(type==DealType.SWAP&&seller!=null)w.squad(buyer.id).filter{!it.youth&&it.id!=w.user.playerId&&it.ca in (p.ca-10)..(p.ca+8)}.minByOrNull{abs(it.ca-p.ca)}?.id?:0 else 0;val swapValue=w.players[swap]?.let{marketValue(w,it)}?:0;val offer=TransferOffer(id=w.nextIds.negotiation++,buyerClubId=buyerClubId,sellerClubId=seller?.id?:0,playerId=p.id,type=type,role=role,fee=(ask*.76-swapValue*.72).toLong().coerceAtLeast(0),wage=wage,signingBonus=(wage*8L),sellOnPercent=5,durationYears=3,releaseClause=(marketValue(w,p)*2.2).toLong(),buyOption=if(type==DealType.LOAN_OPTION)marketValue(w,p) else 0,buyBackClause=if(seller!=null&&w.calendar.season-p.birthYear<=23)(marketValue(w,p)*1.55).toLong() else 0,swapPlayerId=swap,playingTimePromise=roleScore(role),stage=if(seller==null)TransferStage.PLAYER_AGENT else TransferStage.CLUB);w.negotiations[offer.id]=offer;evaluate(w,offer);return offer}
 fun improve(w:World,offerId:Int,kind:String){val o=w.negotiations.getValue(offerId);require(o.status !in listOf(NegotiationStatus.COMPLETED,NegotiationStatus.REJECTED));when(kind){"fee"->o.fee=(o.fee*1.12+500).toLong();"wage"->o.wage=(o.wage*1.10+1).roundToInt();"bonus"->o.signingBonus=(o.signingBonus*1.25+250).toLong();"role"->{o.playingTimePromise=(o.playingTimePromise+10).coerceAtMost(100);o.role=when{o.playingTimePromise>=90->SquadRole.STAR;o.playingTimePromise>=78->SquadRole.STARTER;o.playingTimePromise>=62->SquadRole.ROTATION;else->SquadRole.PROSPECT}};"sellon"->o.sellOnPercent=(o.sellOnPercent+5).coerceAtMost(30)};o.round++;evaluate(w,o)}
 fun evaluate(w:World,o:TransferOffer):TransferOffer{val p=w.players.getValue(o.playerId);val buyer=w.clubs.getValue(o.buyerClubId);val seller=w.clubs[o.sellerClubId];val baseAsk=askingPrice(w,seller,p,o.type);val rivals=w.negotiations.values.count{it.id!=o.id&&it.playerId==o.playerId&&it.buyerClubId!=o.buyerClubId&&it.status in listOf(NegotiationStatus.COUNTER,NegotiationStatus.AGREED)};val ask=(baseAsk*(1+rivals*.08)).toLong();val relation=if(seller!=null)ClubSystems.clubRelation(w,buyer.id,seller.id) else 60;val budgetFit=if(buyer.budget>=o.fee+o.signingBonus)12 else -35;val swapValue=w.players[o.swapPlayerId]?.let{marketValue(w,it)}?:0;val effectiveFee=o.fee+swapValue;val loanStationPenalty=if(p.loanParentClubId!=0&&p.clubId!=o.sellerClubId&&p.loanWeeks>8)6 else 0;o.sellerScore=if(seller==null||p.releaseClause>0&&effectiveFee>=p.releaseClause)100 else (45+(effectiveFee-ask).toDouble()/maxOf(1L,ask)*55+relation/5+(if(p.wantsMove)10 else 0)+(if(o.sellOnPercent>=15)5 else 0)+(if(o.buyBackClause>0&&w.calendar.season-p.birthYear<=23)5 else 0)-loanStationPenalty).roundToInt().coerceIn(0,100);val repGap=buyer.reputation-(seller?.reputation?:buyer.reputation);val interest=TransferInterestSystem.score(w,p,buyer.id);o.playerScore=(24+o.playingTimePromise/3+(o.wage-p.wage).coerceAtLeast(0)/maxOf(1,p.wage+1)*12+repGap/2+p.hidden.ambition/10+interest/4+(if(o.type in listOf(DealType.LOAN,DealType.LOAN_OPTION)&&w.calendar.season-p.birthYear<=22)8 else 0)).coerceIn(0,100);val agentRel=w.agentRelations[p.agentId]?:50;o.agentScore=(35+o.wage/10+(o.signingBonus/maxOf(1L,o.wage*5L)).toInt()*5+agentRel/4+budgetFit).coerceIn(0,100);o.status=when{buyer.budget<o.fee+o.signingBonus->NegotiationStatus.REJECTED;o.sellerScore>=62&&o.playerScore>=62&&o.agentScore>=58->NegotiationStatus.AGREED;o.round>=5&&minOf(o.sellerScore,o.playerScore,o.agentScore)<45->NegotiationStatus.REJECTED;else->NegotiationStatus.COUNTER};o.message=when(o.status){NegotiationStatus.AGREED->"Grundsatzeinigung erreicht. Vor der Registrierung folgt der Medizincheck.";NegotiationStatus.REJECTED->"Die Gespräche sind aktuell festgefahren.";else->"Gegenangebot: Verein ${o.sellerScore}/100 · Spieler ${o.playerScore}/100 · Berater ${o.agentScore}/100"};if(o.status==NegotiationStatus.AGREED&&o.stage !in listOf(TransferStage.MEDICAL,TransferStage.REGISTRATION,TransferStage.COMPLETED)){o.stage=TransferStage.MEDICAL;o.registrationReady=false};return o}
 fun complete(w:World,offerId:Int){val o=w.negotiations.getValue(offerId);if(o.stage !in listOf(TransferStage.MEDICAL,TransferStage.REGISTRATION))evaluate(w,o);require(o.status==NegotiationStatus.AGREED){o.message};if(o.stage==TransferStage.MEDICAL||(o.stage==TransferStage.REGISTRATION&&!o.registrationReady))require(TransferV0518System.medicalAndRegistration(w,o)){o.message};require(o.stage==TransferStage.REGISTRATION&&o.registrationReady){o.message.ifBlank{"Registrierung noch nicht freigegeben."}};val p=w.players.getValue(o.playerId);val buyer=w.clubs.getValue(o.buyerClubId);val seller=w.clubs[o.sellerClubId];require(buyer.budget>=o.fee+o.signingBonus);buyer.budget-=o.fee+o.signingBonus;seller?.let{it.budget+=o.fee};val previous=p.clubId
  when(o.type){DealType.LOAN,DealType.LOAN_OPTION->{p.loanParentClubId=previous;p.loanBuyerClubId=buyer.id;p.loanWeeks=o.loanWeeksRequested.coerceIn(4,104);p.loanOptionFee=o.buyOption;p.loanRecallAllowed=o.recallAllowed;p.loanReturnYouth=p.youth;p.loanReturnYouthSquad=p.youthSquad;p.clubId=buyer.id};else->{p.clubId=buyer.id;p.loanParentClubId=0;p.loanBuyerClubId=0;p.loanWeeks=0;p.loanOptionFee=0}}
  if(o.type==DealType.SWAP&&o.swapPlayerId!=0&&seller!=null){val outgoing=w.players.getValue(o.swapPlayerId);require(outgoing.clubId==buyer.id);outgoing.clubId=seller.id;outgoing.wantsMove=false;outgoing.morale=(outgoing.morale-3).coerceAtLeast(5);seller.dynamics.chemistry=(seller.dynamics.chemistry+1).coerceAtMost(100);buyer.dynamics.chemistry=(buyer.dynamics.chemistry-2).coerceAtLeast(0)}
  p.wage=o.wage;p.contractYears=o.durationYears;p.promisedRole=o.role;p.releaseClause=o.releaseClause;p.buyBackClubId=o.sellerClubId;p.buyBackFee=o.buyBackClause;p.sellOnPercentToPrevious=o.sellOnPercent;p.wantsMove=false;p.youth=o.targetYouthSquad!=null;p.targetYouthSquadApply(o.targetYouthSquad);p.morale=(p.morale+6).coerceAtMost(100);if(p.personalityType(w.calendar.season) in listOf(PersonalityType.LEADER,PersonalityType.BIG_GAME)&&previous!=0)w.clubs[previous]?.dynamics?.let{it.chemistry=(it.chemistry-3).coerceAtLeast(0);it.leadership=(it.leadership-3).coerceAtLeast(0)};o.status=NegotiationStatus.COMPLETED;o.stage=TransferStage.COMPLETED;o.registrationReady=false;o.message="Transfer abgeschlossen.";w.transferHistory.add(0,TransferHistoryEntry(w.calendar.season,w.calendar.absoluteWeek,p.id,previous,buyer.id,o.type,o.fee,"${o.type.label} · ${o.role.label}"));if(previous!=0)WorldFactory.autoLineup(w,previous);WorldFactory.autoLineup(w,buyer.id);seller?.let{ClubSystems.changeClubRelation(w,buyer.id,it.id,if(o.sellerScore>=78)2 else -1)};w.agentRelations[p.agentId]=((w.agentRelations[p.agentId]?:50)+2).coerceAtMost(100);if(buyer.id==w.user.clubId)w.news("Transfer abgeschlossen: ${p.name}","${o.type.label} · Rolle ${o.role.label} · ${o.fee} € · ${o.wage} €/Woche","good")
 }
 private fun exerciseOptionForClub(w:World,p:Player,buyerClubId:Int,announce:Boolean):Boolean{val buyer=w.clubs[buyerClubId]?:return false;val parentId=p.loanParentClubId;val option=p.loanOptionFee;if(p.clubId!=buyerClubId||parentId==0||option<=0||buyer.budget<option)return false;val parent=w.clubs[parentId];buyer.budget-=option;parent?.let{it.budget+=option};p.loanParentClubId=0;p.loanBuyerClubId=0;p.loanWeeks=0;p.loanOptionFee=0;p.contractYears=maxOf(3,p.contractYears);p.morale=(p.morale+5).coerceAtMost(100);WorldFactory.autoLineup(w,buyerClubId);parent?.let{WorldFactory.autoLineup(w,it.id);ClubSystems.changeClubRelation(w,buyerClubId,it.id,1)};if(announce&&buyerClubId==w.user.clubId)w.news("Kaufoption gezogen","${p.name} bleibt dauerhaft im Verein.","good");return true}
 fun exerciseOption(w:World,playerId:Int){val p=w.players.getValue(playerId);require(p.clubId==w.user.clubId&&p.loanParentClubId!=0&&p.loanOptionFee>0){"Keine Kaufoption verfügbar."};require(w.club().budget>=p.loanOptionFee){"Budget reicht nicht."};check(exerciseOptionForClub(w,p,w.user.clubId,true))}
 private fun aiShouldExerciseOption(w:World,p:Player,buyer:Club):Boolean{if(p.loanOptionFee<=0||buyer.budget<p.loanOptionFee)return false;val value=marketValue(w,p);val squad=w.squad(buyer.id).filter{!it.youth&&!it.retired};val avg=squad.map{it.ca}.average().takeIf{!it.isNaN()}?:p.ca.toDouble();val samePosition=squad.filter{it.id!=p.id&&it.position==p.position};val positionalNeed=samePosition.isEmpty()||samePosition.maxOf{it.ca}<p.ca+2;val upside=p.hidden.potential-p.ca;val sporting=p.ca>=avg-2||upside>=8||positionalNeed;val financial=p.loanOptionFee<=value*13/10&&buyer.budget-p.loanOptionFee>=0;return sporting&&financial}
 fun processLoans(w:World){for(p in w.players.values.filter{it.loanWeeks>0}.toList()){val buyer=w.clubs[p.clubId];if(p.loanWeeks<=1&&p.clubId!=w.user.clubId&&p.loanOptionFee>0&&buyer!=null&&aiShouldExerciseOption(w,p,buyer)&&exerciseOptionForClub(w,p,buyer.id,false))continue;p.loanWeeks--;if(p.loanWeeks<=0){val parent=p.loanParentClubId;if(parent in w.clubs){p.clubId=parent;p.loanParentClubId=0;p.loanBuyerClubId=0;p.loanOptionFee=0;WorldFactory.autoLineup(w,parent);buyer?.let{WorldFactory.autoLineup(w,it.id)}}}}}
 fun aiMarket(w:World,rng:SeededRandom){processLoans(w);if(w.calendar.absoluteWeek%2!=0)return;val buyers=w.clubs.values.filter{it.id!=w.user.clubId&&it.budget>3000}.shuffledBy(rng).take(3);for(b in buyers){if(w.squad(b.id).count{!it.youth}>=28)continue;val candidates=w.players.values.filter{!it.retired&&!it.youth&&it.clubId!=b.id&&(it.clubId==0||it.wantsMove||w.clubs[it.clubId]?.budget?.let{v->v<0}==true||TransferInterestSystem.score(w,it,b.id)>=68)&&it.ca<=((w.squad(b.id).filter{!it.youth}.map{it.ca}.average().takeIf{!it.isNaN()}?:50.0)+12)};if(candidates.isEmpty())continue;val p=rng.pick(candidates);val type=if(w.calendar.season-p.birthYear<=22&&rng.chance(.38))DealType.LOAN_OPTION else DealType.BUY;val o=createOffer(w,b.id,p.id,type,if(p.ca>65)SquadRole.STARTER else SquadRole.ROTATION);repeat(3){if(o.status==NegotiationStatus.COUNTER)improve(w,o.id,if(o.sellerScore<62)"fee" else if(o.playerScore<62)"role" else "wage")};if(o.status==NegotiationStatus.AGREED)complete(w,o.id)}}
 private fun <T> List<T>.shuffledBy(rng:SeededRandom):List<T>{val a=toMutableList();for(i in a.lastIndex downTo 1){val j=rng.int(0,i);val t=a[i];a[i]=a[j];a[j]=t};return a}
}

object MatchIntelligence {
 private fun ai(m:LiveMatch,home:Boolean)=if(home)m.homeAi else m.awayAi
 fun preMatch(w:World,c:Club,opp:Club):MatchAiProfile{val o=w.squad(opp.id).filter{!it.youth};val iv=o.filter{it.position==Position.IV};val keeper=o.filter{it.position==Position.TW}.maxByOrNull{it.ca};val flank=o.filter{it.position in listOf(Position.LV,Position.RV,Position.LA,Position.RA)};val weak=when{iv.isNotEmpty()&&iv.map{it.attributes.pace}.average()<48->"Langsame Innenverteidiger";iv.isNotEmpty()&&iv.map{it.attributes.heading}.average()<50->"Schwache Lufthoheit";keeper!=null&&keeper.attributes.passing<45->"Unsicherer Torwart im Aufbau";flank.isNotEmpty()&&flank.map{it.attributes.tackling}.average()<48->"Verwundbare Außenbahn";opp.dynamics.pressingCoordination<42->"Unsauberes Pressing";else->"Keine klare Schwäche"};val approach=when(weak){"Langsame Innenverteidiger"->BuildUp.COUNTER;"Schwache Lufthoheit"->BuildUp.WIDE;"Unsicherer Torwart im Aufbau"->BuildUp.DIRECT;"Verwundbare Außenbahn"->BuildUp.WIDE;"Unsauberes Pressing"->BuildUp.SHORT;else->c.tactics.buildUp};val target=when(weak){"Unsicherer Torwart im Aufbau"->keeper?.id?:0;"Langsame Innenverteidiger","Schwache Lufthoheit"->iv.minByOrNull{if(weak.contains("Langsame"))it.attributes.pace else it.attributes.heading}?.id?:0;else->0};val trap=when{opp.tactics.buildUp in listOf(BuildUp.SHORT,BuildUp.TIKI_TAKA)->"Aufbau auf schwachen Passspieler lenken";opp.tactics.width>=4->"Außen isolieren und Rückpass schließen";else->"Zentrum verdichten und Seitenpass provozieren"};return MatchAiProfile(weak,approach,trap,target,humanErrorRate=(24-c.dynamics.tacticalUnderstanding/6).coerceIn(4,22),tacticalFoulBias=if(c.dynamics.mentalHardness>65)12 else 5,widthBias=if(approach==BuildUp.WIDE)1 else if(approach==BuildUp.SHORT)-1 else 0)}
 fun install(w:World,m:LiveMatch){m.homeAi=preMatch(w,w.clubs.getValue(m.homeId),w.clubs.getValue(m.awayId));m.awayAi=preMatch(w,w.clubs.getValue(m.awayId),w.clubs.getValue(m.homeId))}
 fun playerMentalFactor(w:World,m:LiveMatch,p:Player):Double{val big=m.knockout||w.isDerby(m.homeId,m.awayId)||m.minute>=80;val pressure=abs(m.home.goals-m.away.goals)<=1&&m.minute>=70;return when(p.personalityType(w.calendar.season)){PersonalityType.LEADER->if(big)1.045 else 1.02;PersonalityType.BIG_GAME->if(big)1.08 else 1.01;PersonalityType.CHOKER->if(big||pressure).91 else .99;PersonalityType.LAZY_STAR->if(p.morale<65).92 else .99;PersonalityType.WILD_YOUNGSTER->if(big)if(p.hidden.pressure>=55)1.05 else .94 else 1.02;PersonalityType.PROFESSIONAL->1.025;else->1.0}}
 fun teamFactor(c:Club,attack:Boolean):Double{val d=c.dynamics;val base=if(attack)(d.chemistry*.0012+d.tacticalUnderstanding*.0015+d.opponentPrep*.0008) else (d.chemistry*.0010+d.pressingCoordination*.0016+d.mentalHardness*.0007);return (.82+base).coerceIn(.88,1.14)}
 fun patternFactor(c:Club,key:String)=((c.dynamics.patterns[key]?:30)-50)*.0022+1.0
 fun adapt(w:World,m:LiveMatch,home:Boolean,rng:SeededRandom):String?{val c=w.clubs.getValue(if(home)m.homeId else m.awayId);if(c.id==w.user.clubId)return null;val p=ai(m,home);if(m.minute-p.lastAdjustmentMinute<12)return null;val own=if(home)m.home else m.away;val opp=if(home)m.away else m.home;val behind=own.goals<opp.goals;val ahead=own.goals>opp.goals;val cards=(if(home)m.homeXi else m.awayXi).sumOf{m.yellows[it]?:0}+m.sentOff.count{it in if(home)m.homeXi else m.awayXi};val fatigue=(if(home)m.homeXi else m.awayXi).mapNotNull{w.players[it]?.fitness}.average().takeIf{!it.isNaN()}?:75.0;val patternSeen=opp.possessionTicks>own.possessionTicks*1.25||opp.xg>own.xg+.7;val error=rng.chance(p.humanErrorRate/100.0)
  val mentality=when{behind&&m.minute>=80->5;behind->4;ahead&&m.minute>=72->2;cards>=4||fatigue<58->2;else->3};if(home)m.homeMentality=mentality else m.awayMentality=mentality
  if(error){c.tactics.width=if(c.tactics.width>=4)2 else 5;c.tactics.tempo=(c.tactics.tempo+1).coerceAtMost(5);p.lastAdjustmentMinute=m.minute;p.adaptation++;return "${c.shortName} reagiert unter Druck hektisch und übersteuert die Breite."}
  if(patternSeen){c.tactics.buildUp=p.approach;c.tactics.pressing=(c.tactics.pressing+1).coerceAtMost(if(fatigue<62)3 else 5);p.adaptation++}
  if(behind){c.tactics.tempo=5;c.tactics.line=4;c.tactics.pressing=if(fatigue<60)3 else 5;p.timeWaste=0}else if(ahead&&m.minute>=72){c.tactics.tempo=2;c.tactics.line=2;c.tactics.pressing=if(fatigue<62)2 else 3;p.timeWaste=((m.minute-70)/2).coerceIn(0,10)}
  p.lastAdjustmentMinute=m.minute;return "${c.shortName}: ${if(patternSeen)"Muster erkannt – ${p.weakness}. " else ""}${p.pressingTrap}."
 }
}
