package de.gruenderelf.engine

/** Registrierte Spieler der ukrainischen Premier League 2026/27; Namen, Geburtsjahre, Positionen und Nummern: upl.ua/en/clubs. Ratings sind Spielwerte. */
object UkrainianSquadData {
 val squads:Map<String,List<RealModePlayerSeed>> = mapOf(
  "FC Bukovyna Chernivtsi" to listOf(
   RealModePlayerSeed("Mykyta Bezuhlyi","Ukraine",1995,Position.IV,3,70),
   RealModePlayerSeed("Bohdan Boichuk","Ukraine",1996,Position.ZM,10,70),
   RealModePlayerSeed("Andrii Busko","Ukraine",1997,Position.IV,24,70),
   RealModePlayerSeed("Renat Dadashov","Germany",1999,Position.ST,9,70),
   RealModePlayerSeed("Vitalii Dakhnovskyi","Ukraine",1999,Position.ZM,11,70),
   RealModePlayerSeed("Odinaka Edwin","Nigeria",2003,Position.ZM,18,70),
   RealModePlayerSeed("Mor Talla Gaye","Senegal",1999,Position.ZM,70,70),
   RealModePlayerSeed("Vitalii Hrusha","Ukraine",1994,Position.ZM,25,70),
   RealModePlayerSeed("Oleh Ilin","Ukraine",1997,Position.ZM,97,70),
   RealModePlayerSeed("Danylo Kanevtsev","Ukraine",1996,Position.TW,30,70),
   RealModePlayerSeed("Danylo Karas","Ukraine",1997,Position.IV,2,70),
   RealModePlayerSeed("Mihael Klepac","Croatia",1997,Position.ZM,77,70),
   RealModePlayerSeed("Oleh Kozhushko","Ukraine",1998,Position.ST,7,70),
   RealModePlayerSeed("Danylo Kravchuk","Ukraine",2001,Position.ST,21,70),
   RealModePlayerSeed("Herman Penkov","Ukraine",1994,Position.TW,94,70),
   RealModePlayerSeed("Yevhen Pidlepenets","Ukraine",1998,Position.ZM,12,70),
   RealModePlayerSeed("Vladyslav Pryimak","Ukraine",1996,Position.IV,5,70),
   RealModePlayerSeed("Illia Putria","Ukraine",1998,Position.IV,22,70),
   RealModePlayerSeed("Taras Sakiv","Ukraine",1997,Position.IV,4,70),
   RealModePlayerSeed("Petro Stasiuk","Ukraine",1995,Position.IV,95,70),
   RealModePlayerSeed("Viacheslav Tankovskyi","Ukraine",1995,Position.ZM,6,70),
   RealModePlayerSeed("Vadym Vitenchuk","Ukraine",1997,Position.ZM,44,70),
   RealModePlayerSeed("Maksym Zaderaka","Ukraine",1994,Position.ZM,20,70)
  ),
  "NK Veres Rivne" to listOf(
   RealModePlayerSeed("Mykyta Alexandrov","Ukraine",2004,Position.ST,23,70),
   RealModePlayerSeed("Nathanael Dane Blair","Australia",2004,Position.ST,9,70),
   RealModePlayerSeed("Vitalii Boiko","Ukraine",1997,Position.ZM,18,70),
   RealModePlayerSeed("Danyil Checher","Ukraine",2004,Position.IV,44,70),
   RealModePlayerSeed("Kai Cipot","Slovenia",2001,Position.IV,4,70),
   RealModePlayerSeed("Wesley Da Conceição Duarte Moreira","Brazil",2002,Position.ZM,11,70),
   RealModePlayerSeed("Valentyn Horokh","Ukraine",2001,Position.TW,91,70),
   RealModePlayerSeed("Ihor Kharatin","Ukraine",1995,Position.ZM,14,70),
   RealModePlayerSeed("Fabricio Yan Peishoto Barros Limeira","Brazil",2004,Position.ZM,7,70),
   RealModePlayerSeed("Andre Pereira Gonsalves","Portugal",2003,Position.ZM,19,70),
   RealModePlayerSeed("Mykhailo Protasevych","Ukraine",2004,Position.IV,17,70),
   RealModePlayerSeed("Vladyslav Sharai","Ukraine",1997,Position.ZM,77,70),
   RealModePlayerSeed("Maksym Smiian","Ukraine",2002,Position.IV,2,70),
   RealModePlayerSeed("Konstantinos Stamoulis","Greece",2000,Position.IV,22,70),
   RealModePlayerSeed("Semen Vovchenko","Ukraine",1999,Position.IV,3,70),
   RealModePlayerSeed("Pavlo Bahrii","Ukraine",2005,Position.IV,5,58),
   RealModePlayerSeed("Rostyslav Baran","Ukraine",2005,Position.ZM,88,58),
   RealModePlayerSeed("Guslherme De Jesus Lima","Brazil",2006,Position.ZM,80,58),
   RealModePlayerSeed("Oleksandr Kharechko","Ukraine",2007,Position.TW,13,58),
   RealModePlayerSeed("Luka Khokhashvili","Georgia",2007,Position.IV,30,58)
  ),
  "Dynamo Kyiv" to listOf(
   RealModePlayerSeed("Keasse Paul Henri Bah","Cote d`Ivoire",2004,Position.ZM,42,70),
   RealModePlayerSeed("Kristian Bilovar","Ukraine",2001,Position.IV,40,70),
   RealModePlayerSeed("Volodymyr Brazhko","Ukraine",2002,Position.ZM,6,70),
   RealModePlayerSeed("Vitalii Buialskii","Ukraine",1993,Position.ZM,29,70),
   RealModePlayerSeed("Georgii Bushchan","Ukraine",1994,Position.TW,1,70),
   RealModePlayerSeed("Vladyslav Dubinchak","Ukraine",1998,Position.IV,44,70),
   RealModePlayerSeed("Eduardo Antonio Guerrero Locano","Panama",2000,Position.ST,39,70),
   RealModePlayerSeed("Andrii Iarmolenko","Ukraine",1989,Position.ZM,7,70),
   RealModePlayerSeed("Vladyslav Kabaiev","Ukraine",1995,Position.ZM,22,70),
   RealModePlayerSeed("Tomasz Karol Kedziora","Poland",1994,Position.IV,94,70),
   RealModePlayerSeed("Justin Antonius Lonwijk","Netherlands",1999,Position.ZM,21,70),
   RealModePlayerSeed("Navin Malysh","Ukraine",2003,Position.IV,23,70),
   RealModePlayerSeed("Mykola Mykhailenko","Ukraine",2001,Position.ZM,91,70),
   RealModePlayerSeed("Ruslan Neshcheret","Ukraine",2002,Position.TW,35,70),
   RealModePlayerSeed("Illia Olkhovyi","Ukraine",2003,Position.TW,43,70),
   RealModePlayerSeed("Oleksandr Pikhalonok","Ukraine",1997,Position.ZM,8,70),
   RealModePlayerSeed("Denys Popov","Ukraine",1999,Position.IV,4,70),
   RealModePlayerSeed("Valentyn Rubchynskyi","Ukraine",2002,Position.ZM,15,70),
   RealModePlayerSeed("Mykola Shaparenko","Ukraine",1998,Position.ZM,10,70),
   RealModePlayerSeed("Vladyslav Supriaha","Ukraine",2000,Position.ST,20,70),
   RealModePlayerSeed("Oleksii Sych","Ukraine",2001,Position.IV,5,70),
   RealModePlayerSeed("Aliou Thiaré","Senegal",2003,Position.IV,66,70),
   RealModePlayerSeed("Oleksandr Tymchyk","Ukraine",1997,Position.IV,18,70),
   RealModePlayerSeed("Kostiantyn Vivcharenko","Ukraine",2002,Position.IV,2,70),
   RealModePlayerSeed("Nazar Voloshyn","Ukraine",2003,Position.ZM,9,70)
  ),
  "FC Epicentr" to listOf(
   RealModePlayerSeed("Ivan Bendera","Ukraine",2003,Position.ZM,17,70),
   RealModePlayerSeed("Oleh Bilyk","Ukraine",1998,Position.TW,31,70),
   RealModePlayerSeed("Jon Ceberio Mutuberria","Spain",1996,Position.ZM,10,70),
   RealModePlayerSeed("Nil Coch Montaña","Spain",1998,Position.IV,77,70),
   RealModePlayerSeed("Nikita Fedotov","Ukraine",2000,Position.TW,71,70),
   RealModePlayerSeed("Stepan Hryhorashchuk","Ukraine",2001,Position.IV,3,70),
   RealModePlayerSeed("Oleksandr Klymets","Ukraine",2000,Position.IV,97,70),
   RealModePlayerSeed("Kyrylo Kovalets","Ukraine",1993,Position.ZM,6,70),
   RealModePlayerSeed("Artem Kozak","Ukraine",1998,Position.ZM,59,70),
   RealModePlayerSeed("Ihor Kyriukhantsev","Ukraine",1996,Position.IV,70,70),
   RealModePlayerSeed("Andrii Lipovuz","Ukraine",1998,Position.ZM,28,70),
   RealModePlayerSeed("Valerii Luchkevich","Ukraine",1996,Position.IV,7,70),
   RealModePlayerSeed("Vladyslav Moroz","Ukraine",2001,Position.IV,4,70),
   RealModePlayerSeed("Mykola Myroniuk","Ukraine",2002,Position.ZM,8,70),
   RealModePlayerSeed("Serian Repaj","Albania",2000,Position.IV,13,70),
   RealModePlayerSeed("Carlos Humberto Rojas Mosquera","Spain",2002,Position.ZM,99,70),
   RealModePlayerSeed("Daniel Rueda Bodega","Spain",2002,Position.ZM,21,70),
   RealModePlayerSeed("Raul Tavares Pulido","Spain",1999,Position.ZM,14,70),
   RealModePlayerSeed("Daniil Vashchenko","Ukraine",2005,Position.ZM,27,70),
   RealModePlayerSeed("Maksym Yevpak","Ukraine",2002,Position.ST,15,70),
   RealModePlayerSeed("Yevhen Zaporozhets","Ukraine",1994,Position.ZM,5,70)
  ),
  "Zorya Luhansk" to listOf(
   RealModePlayerSeed("Jakov Bašić","Croatia",1996,Position.ZM,21,70),
   RealModePlayerSeed("Maksym Boiko","Ukraine",2004,Position.ZM,18,70),
   RealModePlayerSeed("Pylyp Budkivskyi","Ukraine",1992,Position.ST,28,70),
   RealModePlayerSeed("Anderson Jordan Da Silva Cordeiro","Brazil",1999,Position.IV,55,70),
   RealModePlayerSeed("Kyrylo Dryshliuk","Ukraine",1999,Position.IV,8,70),
   RealModePlayerSeed("Gabriel Eskinja","Austria",2003,Position.IV,4,70),
   RealModePlayerSeed("Anton Hlushchenko","Ukraine",2004,Position.ZM,14,70),
   RealModePlayerSeed("Ihor Horbach","Ukraine",2004,Position.ST,11,70),
   RealModePlayerSeed("Andrija Janjić","Bosnia & Herzegovina",2002,Position.IV,5,70),
   RealModePlayerSeed("Domagoj Jelavić","Croatia",2001,Position.ZM,27,70),
   RealModePlayerSeed("Illia Karavashchenko","Ukraine",2001,Position.TW,23,70),
   RealModePlayerSeed("Vasyl Kravets","Ukraine",1997,Position.IV,3,70),
   RealModePlayerSeed("Bohdan Kushnirenko","Ukraine",1995,Position.ZM,77,70),
   RealModePlayerSeed("Gerson Leal Rodrigues","Luxembourg",1995,Position.ST,7,70),
   RealModePlayerSeed("Italo Guilherme Machado Henrique","Brazil",2002,Position.IV,40,70),
   RealModePlayerSeed("Artem Macheliuk","Ukraine",1999,Position.IV,39,70),
   RealModePlayerSeed("Ivan Nesterenko","Ukraine",2003,Position.ZM,30,70),
   RealModePlayerSeed("Ihor Perduta","Ukraine",1990,Position.IV,44,70),
   RealModePlayerSeed("Dejan Popara","Bosnia & Herzegovina",2003,Position.ZM,6,70),
   RealModePlayerSeed("Leovigildo Junior Reis Rodrigues","Brazil",1995,Position.IV,10,70),
   RealModePlayerSeed("Vladyslav Rybak","Ukraine",2001,Position.TW,25,70),
   RealModePlayerSeed("Oleksandr Saputin","Ukraine",2003,Position.TW,1,70),
   RealModePlayerSeed("Artem Slesar","Ukraine",2004,Position.ZM,9,70),
   RealModePlayerSeed("Vladlen Yurchenko","Ukraine",1994,Position.ZM,80,70)
  ),
  "Karpaty Lviv" to listOf(
   RealModePlayerSeed("Xeber Alkain Mitxelena","Spain",1997,Position.ZM,70,70),
   RealModePlayerSeed("Vladyslav Babohlo","Moldova",1998,Position.IV,4,70),
   RealModePlayerSeed("Andrii Buleza","Ukraine",2004,Position.IV,5,70),
   RealModePlayerSeed("Jean Henrique Carneiro Pedroso","Brazil",2004,Position.IV,47,70),
   RealModePlayerSeed("Ambrosii Chachua","Ukraine",1994,Position.ZM,8,70),
   RealModePlayerSeed("Joaquin Carlos Cifuentes Xalmet","Spain",1997,Position.ZM,77,70),
   RealModePlayerSeed("Yurii-Volodymyr Hereta","Ukraine",2004,Position.TW,99,70),
   RealModePlayerSeed("Bruno Iglesias Lois","Spain",2003,Position.ZM,21,70),
   RealModePlayerSeed("Yaroslav Karabin","Ukraine",2002,Position.ZM,19,70),
   RealModePlayerSeed("Vitalii Kholod","Ukraine",2004,Position.IV,44,70),
   RealModePlayerSeed("Yan Kostenko","Ukraine",2003,Position.ZM,26,70),
   RealModePlayerSeed("Rostyslav Liakh","Ukraine",2000,Position.IV,73,70),
   RealModePlayerSeed("Denys Miroshnichenko","Ukraine",1994,Position.IV,11,70),
   RealModePlayerSeed("Mohamed Aiman Moukhliss Agmir","Spain",2000,Position.ZM,10,70),
   RealModePlayerSeed("Roman Mysak","Ukraine",1991,Position.TW,80,70),
   RealModePlayerSeed("Nazarii Rusyn","Ukraine",1998,Position.ST,31,70),
   RealModePlayerSeed("Marko Sapuha","Ukraine",2003,Position.ZM,20,70),
   RealModePlayerSeed("Joseph Thibaut Sery","France",2000,Position.ST,9,70),
   RealModePlayerSeed("Tymur Stetskov","Ukraine",1998,Position.IV,55,70),
   RealModePlayerSeed("Roman Vantukh","Ukraine",1998,Position.IV,17,70),
   RealModePlayerSeed("Anton Zhylkin","Ukraine",2003,Position.TW,36,70),
   RealModePlayerSeed("Ivan Сalero Ruiz","Spain",1995,Position.IV,14,70)
  ),
  "Kolos Kovalivka" to listOf(
   RealModePlayerSeed("Mykyta Burda","Ukraine",1995,Position.IV,6,70),
   RealModePlayerSeed("Oleksandr Demchenko","Ukraine",1996,Position.ZM,7,70),
   RealModePlayerSeed("Nika Gagnidze","Georgia",2001,Position.ZM,20,70),
   RealModePlayerSeed("Roman Honcharenko","Ukraine",1993,Position.IV,33,70),
   RealModePlayerSeed("Ibrahim Kane","Mali",2000,Position.ZM,14,70),
   RealModePlayerSeed("Irgi Kasalla","Albania",2002,Position.ZM,90,70),
   RealModePlayerSeed("Daniil Khrypchuk","Ukraine",2003,Position.IV,45,70),
   RealModePlayerSeed("Yurii Klymchuk","Ukraine",1997,Position.ST,70,70),
   RealModePlayerSeed("Eduard Kozik","Ukraine",2003,Position.IV,3,70),
   RealModePlayerSeed("Dmytro Matsapura","Ukraine",2000,Position.TW,1,70),
   RealModePlayerSeed("Valentyn Morhun","Ukraine",2001,Position.TW,51,70),
   RealModePlayerSeed("Denys Ndukve","Ukraine",2000,Position.ST,30,70),
   RealModePlayerSeed("Ivan Pakholiuk","Ukraine",2004,Position.TW,31,70),
   RealModePlayerSeed("Andrii Poniedielnik","Ukraine",1997,Position.IV,77,70),
   RealModePlayerSeed("Arinaldo Rrapaj","Albania",2001,Position.ZM,99,70),
   RealModePlayerSeed("Zurab Rukhadze","Georgia",2003,Position.IV,2,70),
   RealModePlayerSeed("Anton Salabai","Ukraine",2002,Position.ST,17,70),
   RealModePlayerSeed("Oleksandr Savchuk","Ukraine",2004,Position.IV,42,70),
   RealModePlayerSeed("Luka Stankovski","North Macedonia",2002,Position.ZM,10,70),
   RealModePlayerSeed("Ardit Tahiri","Kosovo",2002,Position.ST,11,70),
   RealModePlayerSeed("Elias Miguel Trevizan Telles","Italy",1998,Position.ZM,55,70),
   RealModePlayerSeed("Andriy Tsurikov","Ukraine",1992,Position.IV,9,70)
  ),
  "Kryvbas Kryvyi Rih" to listOf(
   RealModePlayerSeed("Bar Shmuel Enosh Lin","Israel",2004,Position.ZM,18,70),
   RealModePlayerSeed("Oleksandr Kemkin","Ukraine",2002,Position.TW,12,70),
   RealModePlayerSeed("Bohdan Khoma","Ukraine",2003,Position.TW,1,70),
   RealModePlayerSeed("Viacheslav Kulbachuk","Ukraine",2004,Position.IV,5,70),
   RealModePlayerSeed("Geremias Jimmy Lima Mpanzu","Portugal",2002,Position.IV,3,70),
   RealModePlayerSeed("Aharon Roy Nawi (Nabi)","Israel",2004,Position.ZM,17,70),
   RealModePlayerSeed("Denys Pidhurskyi","Ukraine",2003,Position.ZM,6,70),
   RealModePlayerSeed("Yackson Stiven Rivas","Venezuela",2002,Position.ZM,7,70),
   RealModePlayerSeed("Shakeone Sean Satchwell","Jamaica",2004,Position.ST,9,70),
   RealModePlayerSeed("Assane Seck","Senegal",2004,Position.ZM,14,70),
   RealModePlayerSeed("Volodymyr Vilivald","Ukraine",2004,Position.IV,4,70),
   RealModePlayerSeed("Matvii Bodnar","Ukraine",2008,Position.ST,20,58),
   RealModePlayerSeed("Tymur Boiar","Ukraine",2009,Position.IV,45,58),
   RealModePlayerSeed("Tymur Butenko","Ukraine",2006,Position.ZM,25,58),
   RealModePlayerSeed("Oleksii Buzovskyi","Ukraine",2009,Position.IV,62,58),
   RealModePlayerSeed("Oleksandr Chernushkin","Ukraine",2008,Position.ZM,31,58),
   RealModePlayerSeed("Jhonni Santiago Cuiza Cayo","Bolivia",2005,Position.ZM,28,58),
   RealModePlayerSeed("Abdulmajid Mohammed Danladi","Nigeria",2006,Position.TW,41,58),
   RealModePlayerSeed("Artem Dudarenko","Ukraine",2008,Position.TW,33,58),
   RealModePlayerSeed("João Pedro Flores Fernandes De Oliveira Machado","Portugal",2005,Position.IV,22,58)
  ),
  "Kudrivka" to listOf(
   RealModePlayerSeed("Oleksandr Bieliaiev","Ukraine",1999,Position.ZM,21,70),
   RealModePlayerSeed("Kostiantyn Bychek","Ukraine",2000,Position.ZM,77,70),
   RealModePlayerSeed("Artur Dumaniuk","Ukraine",1996,Position.ZM,19,70),
   RealModePlayerSeed("Faites-Prevu Kaya Makosso","Congo",1998,Position.ZM,14,70),
   RealModePlayerSeed("Kyrylo Lavuta","Ukraine",2002,Position.TW,1,70),
   RealModePlayerSeed("Maksym Melnychuk","Ukraine",1999,Position.IV,91,70),
   RealModePlayerSeed("Raymond Frimpong Owusu","Ghana",2002,Position.ST,24,70),
   RealModePlayerSeed("Yevhenii Pasich","Ukraine",1993,Position.IV,42,70),
   RealModePlayerSeed("Ivan Petriak","Ukraine",1994,Position.ZM,7,70),
   RealModePlayerSeed("Rodion Plaksa","Ukraine",2002,Position.ZM,10,70),
   RealModePlayerSeed("Yurii Potimkov","Ukraine",2002,Position.IV,69,70),
   RealModePlayerSeed("Dmytro Semenov","Ukraine",1999,Position.IV,50,70),
   RealModePlayerSeed("Myroslav Serdiuk","Ukraine",1999,Position.IV,17,70),
   RealModePlayerSeed("Kyrylo Siheiev","Ukraine",2004,Position.ZM,66,70),
   RealModePlayerSeed("Yevhenii Smyrnyi","Ukraine",1998,Position.ST,8,70),
   RealModePlayerSeed("Roman Solodarenko","Ukraine",1984,Position.ST,11,70),
   RealModePlayerSeed("Serhii Sten","Ukraine",2002,Position.ZM,71,70),
   RealModePlayerSeed("Denys Svitiukha","Ukraine",2002,Position.ZM,20,70),
   RealModePlayerSeed("Mykola Vechurko","Ukraine",1992,Position.ZM,6,70),
   RealModePlayerSeed("Bohdan Vekliak","Ukraine",1999,Position.IV,22,70),
   RealModePlayerSeed("Reynaldiño Jorge Verley Barrera","Panama",2002,Position.ST,9,70),
   RealModePlayerSeed("Anton Yashkov","Ukraine",1992,Position.TW,37,70)
  ),
  "Livyi Bereh Kyiv" to listOf(
   RealModePlayerSeed("Ernest Astakhov","Ukraine",1998,Position.IV,27,70),
   RealModePlayerSeed("Yevhen Banada","Ukraine",1992,Position.ZM,44,70),
   RealModePlayerSeed("Valerii Bondarenko","Ukraine",1994,Position.IV,4,70),
   RealModePlayerSeed("Artem Cheliadin","Ukraine",1999,Position.ZM,38,70),
   RealModePlayerSeed("Oleksandr Domoleha","Ukraine",2003,Position.TW,23,70),
   RealModePlayerSeed("Denys Ihnatenko","Ukraine",2003,Position.TW,74,70),
   RealModePlayerSeed("Serhii Kosovskyi","Ukraine",1998,Position.ZM,25,70),
   RealModePlayerSeed("Illia Kovalenko","Ukraine",2001,Position.IV,13,70),
   RealModePlayerSeed("Oleh Kryvoruchko","Ukraine",2004,Position.ZM,8,70),
   RealModePlayerSeed("Illia Kvasnytsia","Ukraine",2003,Position.ZM,11,70),
   RealModePlayerSeed("Nikolas Osei Bonsu","Ghana",2001,Position.IV,90,70),
   RealModePlayerSeed("Valerii Samar","Ukraine",2001,Position.IV,5,70),
   RealModePlayerSeed("Dmytro Shastal","Ukraine",1995,Position.ZM,7,70),
   RealModePlayerSeed("Sidnney Silva Santos","Brazil",2000,Position.IV,6,70),
   RealModePlayerSeed("Oleh Sokolov","Ukraine",1999,Position.IV,2,70),
   RealModePlayerSeed("Diego Henrique Souza Da Silva","Brazil",2003,Position.ZM,10,70),
   RealModePlayerSeed("Severin Tatolna","Central African Republic",2002,Position.IV,14,70),
   RealModePlayerSeed("Nazar Voloshyn","Ukraine",2000,Position.ST,21,70),
   RealModePlayerSeed("Vikentii Voloshyn","Ukraine",2001,Position.ZM,15,70),
   RealModePlayerSeed("Nazarii Vorobchak","Ukraine",2000,Position.ZM,17,70),
   RealModePlayerSeed("Andrii Yakymiv","Ukraine",1997,Position.IV,97,70),
   RealModePlayerSeed("Roman Zhmurko","Ukraine",1997,Position.TW,12,70)
  ),
  "LNZ Cherkasy" to listOf(
   RealModePlayerSeed("Mark Assinor","Ghana",2000,Position.ST,90,70),
   RealModePlayerSeed("Tedi Cara","Albania",2000,Position.ZM,77,70),
   RealModePlayerSeed("Ajdi Dajko","Albania",2002,Position.IV,4,70),
   RealModePlayerSeed("Oluwakorede Michael Adedoyin David","Great Britain",2000,Position.ST,99,70),
   RealModePlayerSeed("Talles Brener De Paula","Brazil",1998,Position.ZM,30,70),
   RealModePlayerSeed("Roman Didyk","Ukraine",2002,Position.IV,29,70),
   RealModePlayerSeed("Oleksandr Drambaiev","Ukraine",2001,Position.IV,14,70),
   RealModePlayerSeed("Oleh Horin","Ukraine",2000,Position.ZM,25,70),
   RealModePlayerSeed("Muharrem Jashari","Kosovo",1998,Position.ZM,10,70),
   RealModePlayerSeed("Andrii Kitela","Ukraine",2004,Position.IV,75,70),
   RealModePlayerSeed("Denys Kuzyk","Ukraine",2002,Position.ZM,17,70),
   RealModePlayerSeed("Dmytro Ledvii","Ukraine",2003,Position.TW,1,70),
   RealModePlayerSeed("Nazariy Muravskyy","Ukraine",2000,Position.IV,34,70),
   RealModePlayerSeed("Artur Mykytyshyn","Ukraine",2003,Position.ZM,7,70),
   RealModePlayerSeed("Oleksii Palamarchuk","Ukraine",1991,Position.TW,12,70),
   RealModePlayerSeed("Hennadii Pasich","Ukraine",1993,Position.ZM,11,70),
   RealModePlayerSeed("Yevhenii Pastukh","Ukraine",2004,Position.ZM,19,70),
   RealModePlayerSeed("Artur Riabov","Ukraine",2000,Position.ZM,16,70),
   RealModePlayerSeed("Vitalii Roman","Ukraine",2003,Position.IV,93,70),
   RealModePlayerSeed("Kirill Samoilenko","Ukraine",2001,Position.TW,72,70),
   RealModePlayerSeed("Bohdan Sliubyk","Ukraine",2004,Position.IV,92,70),
   RealModePlayerSeed("Yehor Tverdokhlib","Ukraine",2000,Position.ST,9,70),
   RealModePlayerSeed("Papa Ndiaga Yade","Senegal",2000,Position.ST,37,70)
  ),
  "Obolon Kyiv" to listOf(
   RealModePlayerSeed("Kyrylo Barantsov","Ukraine",2003,Position.TW,12,70),
   RealModePlayerSeed("Maksym Chekh","Ukraine",1999,Position.ZM,6,70),
   RealModePlayerSeed("Nazarii Fedorivskyi","Ukraine",1996,Position.TW,1,70),
   RealModePlayerSeed("Dmytro Kapinus","Ukraine",2003,Position.IV,2,70),
   RealModePlayerSeed("Artem Kulakovskyi","Ukraine",2002,Position.ZM,8,70),
   RealModePlayerSeed("Taras Liakh","Ukraine",2005,Position.ZM,90,70),
   RealModePlayerSeed("Andrii Lomnytskyi","Ukraine",2005,Position.IV,32,70),
   RealModePlayerSeed("Andrii Matkevych","Ukraine",2005,Position.IV,7,70),
   RealModePlayerSeed("Ihor Medynskyi","Ukraine",1993,Position.ZM,13,70),
   RealModePlayerSeed("Taras Moroz","Ukraine",1996,Position.ZM,4,70),
   RealModePlayerSeed("Euhenii Morozko","Ukraine",1993,Position.ZM,17,70),
   RealModePlayerSeed("Dmytro Myshnov","Ukraine",1994,Position.ZM,15,70),
   RealModePlayerSeed("Pavlo Polegenko","Ukraine",1995,Position.IV,28,70),
   RealModePlayerSeed("Kyrylo Prokopchuk","Ukraine",1998,Position.IV,30,70),
   RealModePlayerSeed("Yehor Prokopenko","Ukraine",1998,Position.ZM,24,70),
   RealModePlayerSeed("Yevhenii Shevchenko","Ukraine",1995,Position.IV,5,70),
   RealModePlayerSeed("Denys Shostak","Ukraine",2003,Position.ZM,50,70),
   RealModePlayerSeed("Artem Shulianskyi","Ukraine",2001,Position.ZM,14,70),
   RealModePlayerSeed("Oleh Slobodian","Ukraine",1996,Position.ZM,10,70),
   RealModePlayerSeed("Serhii Sukhanov","Ukraine",1995,Position.ZM,55,70),
   RealModePlayerSeed("Denys Tesliuk","Ukraine",2003,Position.ST,99,70),
   RealModePlayerSeed("Denys Ustymenko","Ukraine",1999,Position.ST,9,70),
   RealModePlayerSeed("Roman Volokhatyi","Ukraine",2000,Position.ZM,20,70),
   RealModePlayerSeed("Vitalii Yermakov","Ukraine",1992,Position.IV,3,70),
   RealModePlayerSeed("Oleksandr Zhovtenko","Ukraine",2005,Position.IV,44,70)
  ),
  "Polissya Zhytomyr" to listOf(
   RealModePlayerSeed("Oleg Kudryk","Ukraine",1996,Position.TW,1,70),
   RealModePlayerSeed("Mykyta Kravchenko","Ukraine",1997,Position.RV,4,70),
   RealModePlayerSeed("Eduard Sarapii","Ukraine",1999,Position.IV,5,70),
   RealModePlayerSeed("Oleksandr Nazarenko","Ukraine",2000,Position.ZM,7,70),
   RealModePlayerSeed("Ruslan Babenko","Ukraine",1992,Position.ZM,8,70),
   RealModePlayerSeed("Oleksandr Filippov","Ukraine",1992,Position.ST,9,70),
   RealModePlayerSeed("Vladyslav Veleten","Ukraine",2002,Position.RA,10,70),
   RealModePlayerSeed("Leandro Livramento Andrade","Portugal",1999,Position.ZM,11,70),
   RealModePlayerSeed("Lindon Emerllahu","Kosovo",2002,Position.ZM,14,70),
   RealModePlayerSeed("Bohdan Mykhailichenko","Ukraine",1997,Position.IV,15,70),
   RealModePlayerSeed("Ilir Krasniqi","Kosovo",2000,Position.ST,16,70),
   RealModePlayerSeed("Oleksandr Andriyevskiy","Ukraine",1994,Position.ZM,18,70),
   RealModePlayerSeed("Volodymyr Shepelev","Ukraine",1997,Position.ZM,19,70),
   RealModePlayerSeed("Yevhenii Volynets","Ukraine",1993,Position.TW,23,70),
   RealModePlayerSeed("Giorgi Maisuradze","Georgia",2002,Position.RV,31,70),
   RealModePlayerSeed("Serhii Chobotenko","Ukraine",1997,Position.IV,44,70),
   RealModePlayerSeed("Maksym Braharu","Ukraine",2002,Position.LA,45,70),
   RealModePlayerSeed("Borys Krushynskyi","Ukraine",2002,Position.ZM,55,70),
   RealModePlayerSeed("Mykola Hayduchyk","Ukraine",1999,Position.ST,89,70),
   RealModePlayerSeed("Igor Krasnopir","Ukraine",2002,Position.ST,95,70)
  ),
  "Metalist 1925 Kharkiv" to listOf(
   RealModePlayerSeed("Denys Antiukh","Ukraine",1997,Position.ZM,9,70),
   RealModePlayerSeed("Joseph Nikolas Arevalo Chaparro","Colombia",2003,Position.ZM,16,70),
   RealModePlayerSeed("Valerii Dubko","Ukraine",2001,Position.IV,37,70),
   RealModePlayerSeed("Peter Mandela Itodo","Nigeria",2003,Position.ST,98,70),
   RealModePlayerSeed("Ivan Kaliuzhnyi","Ukraine",1998,Position.ZM,5,70),
   RealModePlayerSeed("Igor Kogut","Ukraine",1996,Position.ZM,25,70),
   RealModePlayerSeed("Illia Krupskyi","Ukraine",2004,Position.IV,27,70),
   RealModePlayerSeed("Oleksandr Martyniuk","Ukraine",2001,Position.IV,24,70),
   RealModePlayerSeed("Carlos Miguel Paraco Honsales","Venezuela",2003,Position.ST,10,70),
   RealModePlayerSeed("Yevhen Pavliuk","Ukraine",2002,Position.IV,18,70),
   RealModePlayerSeed("Rafael Profini","Argentina",2003,Position.ZM,6,70),
   RealModePlayerSeed("Yaroslav Protsenko","Ukraine",2002,Position.TW,23,70),
   RealModePlayerSeed("Ermir Rashytsia","Albania",2004,Position.ZM,19,70),
   RealModePlayerSeed("Volodymyr Saliuk","Ukraine",2002,Position.IV,13,70),
   RealModePlayerSeed("Artem Shabanov","Ukraine",1992,Position.IV,31,70),
   RealModePlayerSeed("Artem Smoliakov","Ukraine",2003,Position.IV,29,70),
   RealModePlayerSeed("Danylo Varakuta","Ukraine",2001,Position.TW,30,70),
   RealModePlayerSeed("Oleksandr Yatsyk","Ukraine",2003,Position.ZM,8,70),
   RealModePlayerSeed("Heorhii Yermakov","Ukraine",2002,Position.TW,1,70),
   RealModePlayerSeed("Baton Zabergja","Kosovo",2001,Position.ZM,7,70)
  ),
  "Chornomorets Odesa" to listOf(
   RealModePlayerSeed("Danyil Alefirenko","Ukraine",2000,Position.ST,7,70),
   RealModePlayerSeed("Chijioke Kingsley Aniagboso","Nigeria",2004,Position.TW,12,70),
   RealModePlayerSeed("Artur Avahimian","Ukraine",1997,Position.ZM,10,70),
   RealModePlayerSeed("Nazar Baida","Ukraine",2001,Position.TW,16,70),
   RealModePlayerSeed("Vitalii Farasieienko","Ukraine",2003,Position.ST,13,70),
   RealModePlayerSeed("Marian Faryna","Ukraine",2003,Position.IV,74,70),
   RealModePlayerSeed("Moses Jarju","Gambia",2003,Position.IV,24,70),
   RealModePlayerSeed("Muhammed Jobe","Gambia",2004,Position.ZM,30,70),
   RealModePlayerSeed("Andrii Khoma","Ukraine",2001,Position.ST,9,70),
   RealModePlayerSeed("Dmytro Klots","Ukraine",1996,Position.ZM,8,70),
   RealModePlayerSeed("Vladyslav Klymenko","Ukraine",1994,Position.ZM,21,70),
   RealModePlayerSeed("Ivan Kohut","Ukraine",1998,Position.ZM,17,70),
   RealModePlayerSeed("Mykola Kohut","Ukraine",1998,Position.ZM,19,70),
   RealModePlayerSeed("Serhii Korniichuk","Ukraine",2004,Position.IV,22,70),
   RealModePlayerSeed("Maxym Koval","Ukraine",1992,Position.TW,35,70),
   RealModePlayerSeed("Mahomed Kratov","Ukraine",2004,Position.IV,4,70),
   RealModePlayerSeed("Vasyl Kurko","Ukraine",1995,Position.IV,5,70),
   RealModePlayerSeed("Kristian Mba","Nigeria",1999,Position.ST,99,70),
   RealModePlayerSeed("Maksym Melnychenko","Ukraine",2005,Position.ZM,60,70),
   RealModePlayerSeed("Kiril Popov","Ukraine",2003,Position.ST,11,70),
   RealModePlayerSeed("Oleh Pushkarov","Ukraine",2004,Position.IV,27,70)
  ),
  "Shakhtar Donetsk" to listOf(
   RealModePlayerSeed("Irakli Azarov","Georgia",2002,Position.IV,16,70),
   RealModePlayerSeed("Pedro Henrique Azevedo Pereira","Brazil",2002,Position.IV,13,70),
   RealModePlayerSeed("Valerii Bondar","Ukraine",1999,Position.IV,5,70),
   RealModePlayerSeed("Eguinaldo De Sousa Lemos","Brazil",2004,Position.ST,7,70),
   RealModePlayerSeed("Pedro Viktor Delmino Da Silva","Brazil",1998,Position.ZM,10,70),
   RealModePlayerSeed("Kiril Fesiun","Ukraine",2002,Position.TW,23,70),
   RealModePlayerSeed("Alaa Ghram","Tunisia",2001,Position.IV,18,70),
   RealModePlayerSeed("Marlon Gomes Klaudino","Brazil",2003,Position.ZM,6,70),
   RealModePlayerSeed("Oleksandr Karavaiev","Ukraine",1992,Position.IV,20,70),
   RealModePlayerSeed("Dmytro Kryskiv","Ukraine",2000,Position.ZM,8,70),
   RealModePlayerSeed("Alan Agustin Matturro Romero","Italy",2004,Position.IV,28,70),
   RealModePlayerSeed("Mykola Matviienko","Ukraine",1996,Position.IV,22,70),
   RealModePlayerSeed("Gleiker Teodoro Mendoza Barrios","Venezuela",2001,Position.ZM,77,70),
   RealModePlayerSeed("Yehor Nazaryna","Ukraine",1997,Position.ZM,29,70),
   RealModePlayerSeed("Prosper Sopuruchi Obah","Nigeria",2003,Position.ZM,68,70),
   RealModePlayerSeed("Oleh Ocheretko","Ukraine",2003,Position.ZM,27,70),
   RealModePlayerSeed("Dmytro Riznyk","Ukraine",1999,Position.TW,31,70),
   RealModePlayerSeed("Marlon Santos Da Silva Barbosa","Brazil",1995,Position.IV,4,70),
   RealModePlayerSeed("Vinisius Auhustu Tobias Da Silva","Spain/Brazil",2004,Position.IV,17,70),
   RealModePlayerSeed("Lassina Shamste Sudine Frank Traore","Burkina Faso",2001,Position.ST,2,70),
   RealModePlayerSeed("Denys Tvardovskyi","Ukraine",2003,Position.TW,48,70)
  )
 )
 fun playersFor(club:String)=squads[club].orEmpty()
}
